### ISSUE TITLE
readme might mention that it also works with 2.0.4

### ISSUE THREAD

**Issue by az143** [Nephiel/android-graffiti-height-fix#1]
nephiel, thanks for your work - it's awesome, and as a long-time palm user i absolutely love it!

you might mention in the readme that the height fix does work fine with version 2.0.4 of the graffiti package,  which is the last version without ads and which still can be downloaded [here](http://android.pdassi.de/122438/Graffiti_for_Android.html).

regards,
az

**Comment by Nephiel** [comment]
Thanks for the feedback. I have updated the README file.
